package com.sse.app.identity;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import jakarta.validation.constraints.Email;

import java.time.LocalDate;
import java.util.List;

/** Gom các request DTO của phân hệ identity. */
public final class IdentityDtos {
    private IdentityDtos() {}

    public record LoginRequest(@NotBlank String username, @NotBlank String password) {}

    /** Refresh token may be supplied in the request body by mobile clients or by an HttpOnly cookie on web. */
    public record RefreshRequest(String refreshToken) {}
    public record LogoutRequest(String refreshToken) {}

    public record ForgotPasswordRequest(String email, String username) {}

    public record ResetPasswordRequest(@NotBlank String token, @NotBlank @Size(min = 10, max = 128) String newPassword) {}

    public record ChangePasswordRequest(
            @NotBlank String currentPassword,
            @NotBlank @Size(min = 10, max = 128) String newPassword) {}

    public record UpdateMyProfileRequest(
            @Email String email,
            @Size(max = 30) @Pattern(regexp = "^$|^[0-9+ .()\\-]{7,30}$", message = "Số điện thoại không hợp lệ") String phone,
            @Size(max = 1000) String avatarUrl,
            @Size(max = 1000) String address,
            @Size(max = 255) String guardianName,
            @Size(max = 30) String guardianPhone) {}

    public record CreateUserRequest(
            String id,
            @NotBlank String username,
            @NotBlank @Size(min = 10, max = 128) String password,
            @NotBlank String fullName,
            @NotBlank @Pattern(regexp = "ADMIN|TEACHER|STUDENT|PARENT") String role,
            @NotBlank @Email String email,
            @NotBlank @Size(max = 30)
            @Pattern(regexp = "^[0-9+ .()\\-]{7,30}$", message = "Số điện thoại không hợp lệ") String phone,
            String avatarUrl,
            /** Legacy input, ignored: teacher codes are generated by the backend. */
            String teacherCode,
            /** Legacy display value, ignored: the name is resolved from mainSubjectId. */
            String mainSubject,
            String mainSubjectId,
            /** Legacy input, ignored: student codes are generated by the backend. */
            String studentCode,
            String classId,
            String className,
            LocalDate dateOfBirth,
            String gender,
            String placeOfBirth,
            String ethnicity,
            String nationality,
            String address,
            LocalDate enrollmentDate,
            String guardianName,
            String guardianPhone
    ) {}

    public record UpdateUserRequest(
            String fullName,
            String email,
            String phone,
            String avatarUrl,
            String teacherCode,
            String mainSubject,
            String mainSubjectId,
            String studentCode,
            String classId,
            String className,
            LocalDate dateOfBirth,
            String gender,
            String placeOfBirth,
            String ethnicity,
            String nationality,
            String address,
            LocalDate enrollmentDate,
            String guardianName,
            String guardianPhone
    ) {}

    public record AdminResetPasswordRequest(@Size(min = 10, max = 128) String newPassword) {}

    public record LinkChildRequest(@NotBlank String studentId, Boolean primaryContact) {}

    public record ImportRowError(int row, String username, String error) {}
    public record ImportResult(int totalRows, int importedRows, int failedRows, List<ImportRowError> errors) {}

    public record ImportPreviewRow(
            int row,
            String username,
            String fullName,
            String role,
            String classCode,
            String linkedUsername,
            boolean valid,
            String error
    ) {}

    public record ImportPreview(
            String token,
            String checksum,
            long expiresAt,
            int totalRows,
            int validRows,
            int invalidRows,
            List<ImportPreviewRow> rows
    ) {}
}
